name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  unit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: genv/php-cli:8.1
          options: -v ${{ github.workspace }}:/data/
          run: |
            /usr/local/bin/composer install
            /data/vendor/bin/phpunit /data/tests/
