name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  feature:
    runs-on: ubuntu-24.04
    services:
      godanuk:
        image: gibbs/godanuk:latest
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: genv/php-cli:8.4
          options: >-
            -v ${{ github.workspace }}:/data/
            -e API_GITHUB_USERNAME=${{ secrets.API_GITHUB_USERNAME }}
            -e API_GITHUB_ACCESS_TOKEN=${{ secrets.API_GITHUB_ACCESS_TOKEN }}
          run: |
            /usr/local/bin/composer install
            cp phpunit.dist.xml phpunit.xml
            /data/vendor/bin/phpunit /data/tests/
